# Generated by Django 2.2.28 on 2025-02-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picute',
            new_name='picture',
        ),
    ]
